import os
from dataclasses import dataclass

import requests


@dataclass
class GenerationResult:
    content: str
    demo_mode: bool = False


class GeminiDocumentGenerator:
    def __init__(self):
        self.api_key = os.getenv("GEMINI_API_KEY", "").strip()
        self.model = os.getenv("GEMINI_MODEL", "gemini-3.5-flash").strip()
        self.client = bool(self.api_key)

    def generate_document(
        self,
        document_type: str,
        parties: str,
        terms: str,
        dates: str,
    ) -> GenerationResult:

        if not self.api_key:
            return GenerationResult(
                content=self._demo_document(
                    document_type,
                    parties,
                    terms,
                    dates,
                ),
                demo_mode=True,
            )

        prompt = f"""
Create a professional legal document.

Document Type: {document_type}
Parties: {parties}
Terms & Conditions: {terms}
Effective Date: {dates}

Write a complete professional legal document with:
- Clear title
- Proper headings
- Numbered clauses
- Important terms
- Signature sections

Use simple, formal legal language.

This is a document drafting assistant, not legal advice.
"""

        url = (
            f"https://generativelanguage.googleapis.com/v1beta/models/"
            f"{self.model}:generateContent?key={self.api_key}"
        )

        payload = {
            "contents": [
                {
                    "parts": [
                        {
                            "text": prompt
                        }
                    ]
                }
            ]
        }

        response = requests.post(
            url,
            json=payload,
            timeout=60,
        )

        response.raise_for_status()

        data = response.json()

        try:
            content = data["candidates"][0]["content"]["parts"][0]["text"]
        except (KeyError, IndexError, TypeError):
            content = ""

        if not content:
            raise RuntimeError("Gemini returned an empty response.")

        return GenerationResult(
            content=content,
            demo_mode=False,
        )

    def _demo_document(
        self,
        document_type: str,
        parties: str,
        terms: str,
        dates: str,
    ) -> str:

        return f"""LEGAL DOCUMENT

Document Type:
{document_type}

Parties:
{parties}

Terms:
{terms}

Dates:
{dates}

AGREEMENT

The parties agree to the terms described above.

This is a demo document generated by LegalEase.
Please configure GEMINI_API_KEY for AI-generated documents.

SIGNATURES

Party 1: ______________________

Party 2: ______________________
"""
