import os
from dataclasses import dataclass
try:
    from google import genai
except ImportError:
    genai = None
@dataclass
class GenerationResult:
    content: str
    demo_mode: bool = False


class GeminiDocumentGenerator:
    def __init__(self):
        self.api_key = os.getenv("GEMINI_API_KEY")
        self.model = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

        self.client = None

        if self.api_key:
            self.client = None
            self.client = genai.Client(api_key=self.api_key)

    def generate_document(
        self,
        document_type: str,
        parties: str,
        terms: str,
        dates: str,
    ) -> GenerationResult:

        if not self.client:
            return GenerationResult(
                content=self._demo_document(
                    document_type, parties, terms, dates
                ),
                demo_mode=True,
            )

        prompt = f"""
Create a professional legal document.

Document Type: {document_type}
Parties: {parties}
Terms: {terms}
Dates: {dates}

Write the document clearly with suitable headings,
clauses, and signature sections.

This is a document drafting assistant, not legal advice.
"""

        response = self.client.models.generate_content(
            model=self.model,
            contents=prompt,
            config={
                "http_options": {
                    "timeout": 30000
                }
            },
        )

        return GenerationResult(
            content=response.text or "",
            demo_mode=False,
        )

    def _demo_document(
        self,
        document_type: str,
        parties: str,
        terms: str,
        dates: str,
    ) -> str:

        return f"""LEGAL DOCUMENT

Document Type:
{document_type}

Parties:
{parties}

Terms:
{terms}

Dates:
{dates}

AGREEMENT

The parties agree to the terms described above.

This is a demo document generated by LegalEase.
Please configure GEMINI_API_KEY for AI-generated documents.

SIGNATURES

Party 1: ______________________

Party 2: ______________________
"""
